

[tool.mypy]
python_version = "3.10"
strict = true
warn_return_any = true
ignore_missing_imports = false

[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 120